a

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -346,16 +346,16 @@ jobs:
       - checkout
       - run:
           name: check if changed
-          command: |
-            if [ npx lerna changed -a -eq 0 ]
-            then
-              echo "Success: I found IP address in file."
-              exit 0
-            else
-              echo "Failure: I did not found IP address in file. Script failed" >&2
-              circleci-agent step halt
-              exit 0
-            fi
+#          command: |
+#            npx lerna changed -a
+#            if [ $? -eq 0 ]
+#            then
+#              echo "Success: I found IP address in file."
+#              exit 0
+#            else
+#              echo "Failure: I did not found IP address in file. Script failed" >&2
+#              circleci-agent step halt
+#            fi
 #      - run:
 #          name: all good
 #          command: echo all good
